/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonny
 */
public class ConsultarHabitacion extends javax.swing.JDialog {

    private ArrayList<String> lineasLeer;
    private InformacionHuespedes info;
    private String habitacion;
    /**
     * Creates new form ConsultarHabitacion
     */
    public ConsultarHabitacion(java.awt.Frame parent, boolean modal, InformacionHuespedes hues) {
        super(parent, modal);
        initComponents();
        this.lineasLeer = new ArrayList<>();
        this.info = hues;
        leerHabitacionesCreadas();
        manejoArchivo();
        /**
         * Objetos que cumplen funciones de efectos visuales en la ventana donde
         * se realizarán acciones.
        */
        this.setLocationRelativeTo(this);
        this.setTitle("LosChinches-consultar-habitacion");
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(153, 255, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tNumeroHabitacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tValorPorDia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tCapacidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tDisponibilidad = new javax.swing.JTextField();
        tDescripcion = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tConsulta = new javax.swing.JTextField();
        comboListaHabitaciones = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bAsignarHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("Consulta de habitaciones");

        jLabel1.setText("Número de la habitación:");

        tNumeroHabitacion.setEditable(false);
        tNumeroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumeroHabitacionActionPerformed(evt);
            }
        });

        jLabel3.setText("Costo por día (COP)");

        tValorPorDia.setEditable(false);

        jLabel2.setText("Capacidad:");

        tCapacidad.setEditable(false);

        jLabel5.setText("Disponibilidad:");

        tDisponibilidad.setEditable(false);
        tDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDisponibilidadActionPerformed(evt);
            }
        });

        tDescripcion.setEditable(false);
        tDescripcion.setToolTipText("");
        tDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescripcionActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(153, 255, 153));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel6.setText("Descripción:");

        jLabel7.setText("Número de la habitación que desea consultar:");

        tConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tConsultaActionPerformed(evt);
            }
        });

        comboListaHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        comboListaHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListaHabitacionesActionPerformed(evt);
            }
        });

        jLabel8.setText("Habitaciones disponibles:");

        bAsignarHabitacion.setBackground(new java.awt.Color(153, 255, 153));
        bAsignarHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAsignarHabitacion.setText("Asignar habitación");
        bAsignarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsignarHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(37, 37, 37)
                                    .addComponent(tValorPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(49, 49, 49))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(37, 37, 37)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tDisponibilidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tCapacidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(comboListaHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bAsignarHabitacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jLabel4)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tValorPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tDisponibilidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(14, 14, 14))))
                    .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboListaHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAsignarHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel4)
                    .addContainerGap(456, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNumeroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumeroHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumeroHabitacionActionPerformed

    private void tDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDisponibilidadActionPerformed

    }//GEN-LAST:event_tDisponibilidadActionPerformed

    private void tDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescripcionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void tConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tConsultaActionPerformed
        manejoArchivo();
        tConsulta.setText("");
    }//GEN-LAST:event_tConsultaActionPerformed

    private void comboListaHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListaHabitacionesActionPerformed
        if ((String) (comboListaHabitaciones.getSelectedItem()) != "---") {
            try {
                Properties propiedad = new Properties();
                propiedad.load(new FileInputStream("C:\\Users\\Gestec\\Desktop\\Hotel\\" + (String) (comboListaHabitaciones.getSelectedItem()) + ".properties"));

                tNumeroHabitacion.setText(propiedad.getProperty("NumeroDeHabitacion"));
                tCapacidad.setText(propiedad.getProperty("Capacidad"));
                tValorPorDia.setText(propiedad.getProperty("CostoPorDia"));
                tDescripcion.setText(propiedad.getProperty("Descripcion"));
                tDisponibilidad.setText(propiedad.getProperty("Disponibilidad"));
                
                ImageIcon foto = new ImageIcon(propiedad.getProperty("Fotografia"));
                Image ajuste = foto.getImage().getScaledInstance(labelFoto.getWidth(), labelFoto.getHeight(), Image.SCALE_SMOOTH);
                Icon imagenAjustada = new ImageIcon(ajuste);
        
                labelFoto.setIcon(imagenAjustada);
            } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "La habitación que está consultando no existe o fue revocada recientemente.");
            }
        } else {
            tNumeroHabitacion.setText("");
            tCapacidad.setText("");
            tDescripcion.setText("");
            tValorPorDia.setText("");
            tDisponibilidad.setText("");
        }
    }//GEN-LAST:event_comboListaHabitacionesActionPerformed

    private void bAsignarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsignarHabitacionActionPerformed

        if(!((String)(comboListaHabitaciones.getSelectedItem())).equals("---")){
            String habitacionSeleccionada = (String)(comboListaHabitaciones.getSelectedItem());
            this.info.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una habitación.");
        }
        
    }//GEN-LAST:event_bAsignarHabitacionActionPerformed

    public void manejoArchivo(){
        String numeroConsulta = tConsulta.getText();
        if(!numeroConsulta.equals("")){
        try {
                Properties propiedad = new Properties();
                propiedad.load(new FileInputStream("C:\\Users\\Gestec\\Desktop\\Hotel\\Hab_"+numeroConsulta+".properties"));

                tNumeroHabitacion.setText(propiedad.getProperty("NumeroDeHabitacion"));
                tCapacidad.setText(propiedad.getProperty("Capacidad"));
                tValorPorDia.setText(propiedad.getProperty("CostoPorDia"));
                tDescripcion.setText(propiedad.getProperty("Descripcion"));
                tDisponibilidad.setText(propiedad.getProperty("Disponibilidad"));
                
                ImageIcon foto = new ImageIcon(propiedad.getProperty("Fotografia"));
                Image ajuste = foto.getImage().getScaledInstance(labelFoto.getWidth(), labelFoto.getHeight(), Image.SCALE_SMOOTH);
                Icon imagenAjustada = new ImageIcon(ajuste);
        
                labelFoto.setIcon(imagenAjustada);
            }
    catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "No hay habitación con ese número.");
                }
            }
    }
    
    public void leerHabitacionesCreadas() {
        try {
            File archivo = new File("C:\\Users\\Gestec\\Desktop\\Hotel\\HabitacionesCreadas.txt");
            Scanner leer = new Scanner(archivo);
            Properties propiedad = new Properties();
            int i = 0;
            while (leer.hasNextLine()) {
                lineasLeer.add(leer.nextLine());
                propiedad.load(new FileInputStream("C:\\Users\\Gestec\\Desktop\\Hotel\\"+lineasLeer.get(i)+".properties"));
                if(propiedad.getProperty("Disponibilidad").equals("Si")){
                    comboListaHabitaciones.addItem(lineasLeer.get(i));
                }
                i++;
            }
        } catch (IOException exception) {
            JOptionPane.showMessageDialog(null, exception);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAsignarHabitacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboListaHabitaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JTextField tCapacidad;
    private javax.swing.JTextField tConsulta;
    private javax.swing.JTextField tDescripcion;
    private javax.swing.JTextField tDisponibilidad;
    private javax.swing.JTextField tNumeroHabitacion;
    private javax.swing.JTextField tValorPorDia;
    // End of variables declaration//GEN-END:variables
}
