/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import hotel.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonny
 */
public class CreacionHabitaciones extends javax.swing.JDialog {
    hotel.Hotel hotel;
    private Properties propiedades;
    private OutputStream archivo;
    private Properties lector;
    private int i;
    private ArrayList<String> habitacionNumero;
    /**
     * Creates new form CreacionHabitaciones
     */
    public CreacionHabitaciones(java.awt.Frame parent, boolean modal, hotel.Hotel hotel) {
        super(parent, modal);
        this.hotel = hotel;
        this.propiedades = new Properties();
        this.lector = new Properties();
        i=0;
        this.habitacionNumero = new ArrayList<>();
        initComponents();
         /**
         * Objetos que cumplen funciones de efectos visuales en la ventana donde
         * se realizarán acciones.
         */
        this.setLocationRelativeTo(this);
        this.setTitle("LosChinches-crear-habitacion");
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(153, 255, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tNumeroHabitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tCapacidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tValorPorDia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tFoto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tDescripcion = new javax.swing.JTextField();
        bCrear = new javax.swing.JButton();
        fotoHabitacion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Número de la habitación:");

        tNumeroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumeroHabitacionActionPerformed(evt);
            }
        });

        jLabel2.setText("Capacidad:");

        jLabel3.setText("Costo por día (COP)");

        jLabel5.setText("Foto:");

        tFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFotoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Descripción:");

        tDescripcion.setToolTipText("");
        tDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescripcionActionPerformed(evt);
            }
        });

        bCrear.setBackground(new java.awt.Color(153, 255, 153));
        bCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bCrear.setText("Crear Habitación");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("Creación de habitaciones");

        btnSalir.setBackground(new java.awt.Color(153, 255, 153));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel3))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel2)))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(71, 71, 71)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tValorPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fotoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tValorPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3))
                            .addComponent(fotoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNumeroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumeroHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumeroHabitacionActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
   
        if(tNumeroHabitacion.equals("") || tCapacidad.getText().equals("") || tDescripcion.getText().equals("") || tFoto.getText().equals("") || tValorPorDia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
        }
        else{
            String numero = tNumeroHabitacion.getText();
            String descripcion = tDescripcion.getText();
            String foto = tFoto.getText();
            double valorPorDia = Double.valueOf(tValorPorDia.getText());
            int capacidad = Integer.parseInt(tCapacidad.getText());
            this.hotel.crearHabitacion(numero, capacidad, descripcion, valorPorDia, foto);
            JOptionPane.showMessageDialog(null, "¡La habitación ha sido creada exitiosamente!");
            manejoDeArchivo();
            tNumeroHabitacion.setText("");
            tDescripcion.setText("");
            tCapacidad.setText("");
            tFoto.setText("");
            tValorPorDia.setText("");
        }
        
    }//GEN-LAST:event_bCrearActionPerformed

    private void tFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFotoActionPerformed
        ImageIcon foto = new ImageIcon(tFoto.getText()+".jpg");
        Image ajuste = foto.getImage().getScaledInstance(fotoHabitacion.getWidth(), fotoHabitacion.getHeight(), Image.SCALE_SMOOTH);
        Icon imagenAjustada = new ImageIcon(ajuste);
        
        fotoHabitacion.setIcon(imagenAjustada);
    }//GEN-LAST:event_tFotoActionPerformed

    private void tDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescripcionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void manejoDeArchivo(){      
        
        try{
            this.archivo = new FileOutputStream("Hab_"+tNumeroHabitacion.getText()+".properties"); 
            propiedades.setProperty("NumeroDeHabitacion", tNumeroHabitacion.getText());
            propiedades.setProperty("Capacidad", tCapacidad.getText());
            propiedades.setProperty("CostoPorDia", "$"+tValorPorDia.getText());
            propiedades.setProperty("Descripcion", tDescripcion.getText());
            propiedades.setProperty("Disponibilidad", "Si");
            propiedades.setProperty("Fotografia", tFoto.getText()+".jpg");
            propiedades.store(archivo, "Información de la habitacion");
            
            this.habitacionNumero.add("Hab_"+tNumeroHabitacion.getText());
            FileWriter escribir = new FileWriter("C:\\Users\\Gestec\\Desktop\\Hotel\\HabitacionesCreadas.txt", true);
                    
            escribir.write(this.habitacionNumero.get(i));
            escribir.write("\n");
            escribir.close();
            i++;
                
            }
            catch (IOException exception){
                JOptionPane.showMessageDialog(null, exception);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fotoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tCapacidad;
    private javax.swing.JTextField tDescripcion;
    private javax.swing.JTextField tFoto;
    private javax.swing.JTextField tNumeroHabitacion;
    private javax.swing.JTextField tValorPorDia;
    // End of variables declaration//GEN-END:variables
}
